### ISSUE TITLE
Better screenshot

### ISSUE THREAD

**Issue by zenorocha** [dracula/jdownloader2#2]
Hey @ixanza, the current screenshot makes it really hard to see the theme in action since the screen resolution is quite big. Can you take a new screenshot with more zoom or a different resolution, so that we can see the theme better?

Thanks!

**Comment by ixanza** [comment]
Hey yeah sure. Would any of these work?

![image](https://user-images.githubusercontent.com/5535758/155062577-e640b346-1de0-4171-bc84-77c42e3910d2.png)
![image](https://user-images.githubusercontent.com/5535758/155062595-b95e25fa-37cc-46a8-82a5-e0c39ac3aa32.png)
![image](https://user-images.githubusercontent.com/5535758/155062625-1ba42da9-4491-44d5-8767-30a6d1ab6b72.png)

**Comment by ixanza** [comment]
As an additional to the instructions, I had a friend say the folder /cfg/laf might not exist if Jdownloader2 was not restarted after applying the theme, so I would like to add to say "Create the folders if not present"

**Comment by zenorocha** [comment]
I like this one since it shows the in-progress status: 
![image](https://user-images.githubusercontent.com/398893/155269349-fc34bc6f-9e01-45e7-a87e-7c2d336a1d75.png)

Feel free to update the INSTALL.md instructions too.

**Comment by ixanza** [comment]
alright changes have been made. Thanks

**Comment by zenorocha** [comment]
Thanks!
