### ISSUE TITLE
White Progress Bar

### ISSUE THREAD

**Issue by Quest79** [dracula/jdownloader2#6]
This looks terrible, out of place for the theme and out of place for a darkmode centric theme overall.

Is there a chance we can get information on how to edit this to be one of the proper Dracula colors or to possibly have an alternative laf? Also Im unable to change font size after selecting this theme but I cannot tell if its related to this theme or not yet. 

Great job overall!

**Comment by ixanza** [comment]
Hey I'm so sorry! I've been busy with work and life. Yeah the white on the progress bar looks out of place but i'm not sure what color would go well there. font size is weird in jdownloader2. I'll reinstall and check in a few days.

**Comment by Quest79** [comment]
No problem at all hope all is going well1 :)

On the official color pallet for the theme i was thinking ne of these maybe? Anything other than white would be an improvement. Still looks great though!

[https://i.imgur.com/7sJcCj8.png](url)

**Comment by ixanza** [comment]
@Quest79 I tried looking at all the configs. ProgresBar seemed to be the most relevant but it's not white and and I can't find the relevant setting for that I'm afraid. closing this until I find a solution

**Comment by GATOQSECOMIO** [comment]
any news with the font size?
