### ISSUE TITLE
Wrong filename

### ISSUE THREAD

**Issue by Lucki** [dracula/jdownloader2#7]
The install steps aren't correct and will fail in the current form:

https://github.com/dracula/jdownloader2/blob/c02492d12d092d75a88fb9723aaba75b9b1f7a5e/INSTALL.md?plain=1#L17

The correct filename is `FlatDarculaLaf.json` - yes, on linux that's a different file.

**Comment by ixanza** [comment]
Thanks, I have amended the readme to specifically mention `FlatDarculaLaf.json`
